""" Functions for summarising data generated by edo. """

from pathlib import Path

import pandas as pd

from edo_exp.summarise import get_extremes


HERE = Path(__file__).parent
TEST_DATA_PATH = HERE / "data"
SUMMARY_PATH = HERE / "summary"
TRIAL_FITNESS = pd.read_csv(TEST_DATA_PATH / "fitness.csv")
MAX_GEN = TRIAL_FITNESS["generation"].max()
SIZE = TRIAL_FITNESS["individual"].max()


def test_get_extremes():
    """ Test that the extreme cases can be recorded. """

    get_extremes(TEST_DATA_PATH, SUMMARY_PATH, TRIAL_FITNESS)

    for case in ("min", "median", "max"):

        case_path = SUMMARY_PATH / case
        assert (case_path / "main.csv").exists()
        assert (case_path / "main.meta").exists()


def test_get_trial_info():
    """ Test that the information of the trial can be summarised. """

    pass
